// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/sunr3d/05-08-2025/models"
)

// Database is an autogenerated mock type for the Database type
type Database struct {
	mock.Mock
}

// CountArchivesInProcess provides a mock function with given fields: ctx
func (_m *Database) CountArchivesInProcess(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountArchivesInProcess")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteArchive provides a mock function with given fields: ctx, id
func (_m *Database) DeleteArchive(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteArchive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetArchive provides a mock function with given fields: ctx, id
func (_m *Database) GetArchive(ctx context.Context, id string) (*models.Archive, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetArchive")
	}

	var r0 *models.Archive
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Archive, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Archive); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Archive)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveArchive provides a mock function with given fields: ctx, archive
func (_m *Database) SaveArchive(ctx context.Context, archive *models.Archive) error {
	ret := _m.Called(ctx, archive)

	if len(ret) == 0 {
		panic("no return value specified for SaveArchive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Archive) error); ok {
		r0 = rf(ctx, archive)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDatabase creates a new instance of Database. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatabase(t interface {
	mock.TestingT
	Cleanup(func())
}) *Database {
	mock := &Database{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
